templateDir: ./sdk-resources/resources
packageName: v3
packageVersion: 1.0.4
generateInterfaces: false
enumClassPrefix: false
disallowAdditionalPropertiesIfNotPresent: false
useOneOfDiscriminatorLookup: false
